name: aku_dimana
description: Apps sederhana untuk mendeteksi lagi dimana

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.7
  geolocator: ^4.0.2
  share: ^0.6.1+1
  url_launcher: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "img/logo.png"

flutter:
  uses-material-design: true

